"""phase2_score_historique

ID de révision : d95585c5520c
Révisions précédentes : 9ebe4cf720d4
Créée le : 2026-05-30 22:43:55.219798
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Identifiants de révision
revision: str = 'd95585c5520c'
down_revision: Union[str, None] = '9ebe4cf720d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Application de la migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('score_historique',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('utilisateur_id', sa.UUID(), nullable=False),
    sa.Column('score_total', sa.Integer(), nullable=False),
    sa.Column('facteur_anciennete_sim', sa.Float(), nullable=False),
    sa.Column('facteur_mobile_money', sa.Float(), nullable=False),
    sa.Column('facteur_geographie', sa.Float(), nullable=False),
    sa.Column('facteur_reseau_contacts', sa.Float(), nullable=False),
    sa.Column('date_calcul', sa.DateTime(timezone=True), nullable=False),
    sa.Column('methode', sa.String(length=50), nullable=False),
    sa.Column('donnees_brutes', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], name=op.f('fk_score_historique_utilisateur_id_utilisateur'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_score_historique'))
    )
    op.create_index(op.f('ix_score_historique_date_calcul'), 'score_historique', ['date_calcul'], unique=False)
    op.create_index(op.f('ix_score_historique_utilisateur_id'), 'score_historique', ['utilisateur_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Annulation de la migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_score_historique_utilisateur_id'), table_name='score_historique')
    op.drop_index(op.f('ix_score_historique_date_calcul'), table_name='score_historique')
    op.drop_table('score_historique')
    # ### end Alembic commands ###
