"""ajout_colonne_nombre_articles

ID de révision : f106f41c6209
Révisions précédentes : a3a7b0514059
Créée le : 2026-10-05 13:52:59.905564
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Identifiants de révision
revision: str = 'f106f41c6209'
down_revision: Union[str, None] = 'a3a7b0514059'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Application de la migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('colis', sa.Column('nombre_articles', sa.Integer(), server_default='1', nullable=False))
    op.drop_constraint('uq_ordonnances_numero', 'ordonnances', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Annulation de la migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_ordonnances_numero', 'ordonnances', ['numero_ordonnance'])
    op.drop_column('colis', 'nombre_articles')
    # ### end Alembic commands ###
