"""Ajout table journal_audit

ID de révision : b5dcd915976e
Révisions précédentes : d5384d20c28b
Créée le : 2026-07-16 17:46:40.141889
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# Identifiants de révision
revision: str = 'b5dcd915976e'
down_revision: Union[str, None] = 'd5384d20c28b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Application de la migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ui_module_enabled', table_name='ui_module_permissions')
    op.drop_index('ix_ui_module_module', table_name='ui_module_permissions')
    op.drop_index('ix_ui_module_role', table_name='ui_module_permissions')
    op.drop_table('ui_module_permissions')
    op.alter_column('alertes_police', 'domaine_id',
               existing_type=sa.UUID(),
               comment='Domaine de rattachement',
               existing_nullable=True)
    op.alter_column('alertes_police', 'departement_id',
               existing_type=sa.UUID(),
               comment='Département de rattachement',
               existing_nullable=True)
    op.alter_column('enrolements_police', 'domaine_id',
               existing_type=sa.UUID(),
               comment='Domaine de rattachement',
               existing_nullable=True)
    op.alter_column('enrolements_police', 'departement_id',
               existing_type=sa.UUID(),
               comment='Département de rattachement',
               existing_nullable=True)
    op.alter_column('historique_recherches_police', 'domaine_id',
               existing_type=sa.UUID(),
               comment='Domaine de rattachement',
               existing_nullable=True)
    op.alter_column('historique_recherches_police', 'departement_id',
               existing_type=sa.UUID(),
               comment='Département de rattachement',
               existing_nullable=True)
    op.alter_column('notes_internes', 'domaine_id',
               existing_type=sa.UUID(),
               comment='Domaine de rattachement',
               existing_nullable=True)
    op.alter_column('notes_internes', 'departement_id',
               existing_type=sa.UUID(),
               comment='Département de rattachement',
               existing_nullable=True)
    op.drop_constraint('uq_ordonnances_numero', 'ordonnances', type_='unique')
    op.alter_column('signalements_fraude', 'domaine_id',
               existing_type=sa.UUID(),
               comment='Domaine de rattachement',
               existing_nullable=True)
    op.alter_column('signalements_fraude', 'departement_id',
               existing_type=sa.UUID(),
               comment='Département de rattachement',
               existing_nullable=True)
    op.drop_constraint('signalements_fraude_traite_par_id_fkey', 'signalements_fraude', type_='foreignkey')
    op.drop_column('signalements_fraude', 'priorite')
    op.drop_column('signalements_fraude', 'traite_par_id')
    op.drop_column('signalements_fraude', 'notes_traitement')
    op.drop_column('utilisateur', 'ui_layout')
    op.drop_column('utilisateur', 'modules_overrides')
    op.alter_column('verification_cni', 'mrz_ligne_1',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=30),
               existing_nullable=True)
    op.alter_column('verification_cni', 'mrz_ligne_2',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=30),
               existing_nullable=True)
    op.alter_column('verification_cni', 'mrz_ligne_3',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=30),
               existing_nullable=True)
    op.alter_column('verifications_police', 'domaine_id',
               existing_type=sa.UUID(),
               comment='Domaine de rattachement',
               existing_nullable=True)
    op.alter_column('verifications_police', 'departement_id',
               existing_type=sa.UUID(),
               comment='Département de rattachement',
               existing_nullable=True)
    op.drop_column('verifications_police', 'localisation_adresse')
    op.drop_column('verifications_police', 'motif_verification')
    op.drop_column('verifications_police', 'personne_telephone')
    op.drop_column('verifications_police', 'personne_email')
    op.drop_column('verifications_police', 'localisation_lat')
    op.drop_column('verifications_police', 'localisation_lng')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Annulation de la migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verifications_police', sa.Column('localisation_lng', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('verifications_police', sa.Column('localisation_lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('verifications_police', sa.Column('personne_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('verifications_police', sa.Column('personne_telephone', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('verifications_police', sa.Column('motif_verification', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('verifications_police', sa.Column('localisation_adresse', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('verifications_police', 'departement_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Département de rattachement',
               existing_nullable=True)
    op.alter_column('verifications_police', 'domaine_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Domaine de rattachement',
               existing_nullable=True)
    op.alter_column('verification_cni', 'mrz_ligne_3',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('verification_cni', 'mrz_ligne_2',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('verification_cni', 'mrz_ligne_1',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.add_column('utilisateur', sa.Column('modules_overrides', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True))
    op.add_column('utilisateur', sa.Column('ui_layout', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('signalements_fraude', sa.Column('notes_traitement', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('signalements_fraude', sa.Column('traite_par_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('signalements_fraude', sa.Column('priorite', sa.VARCHAR(length=20), server_default=sa.text("'moyenne'::character varying"), autoincrement=False, nullable=True))
    op.create_foreign_key('signalements_fraude_traite_par_id_fkey', 'signalements_fraude', 'utilisateur', ['traite_par_id'], ['id'], ondelete='SET NULL')
    op.alter_column('signalements_fraude', 'departement_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Département de rattachement',
               existing_nullable=True)
    op.alter_column('signalements_fraude', 'domaine_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Domaine de rattachement',
               existing_nullable=True)
    op.create_unique_constraint('uq_ordonnances_numero', 'ordonnances', ['numero_ordonnance'])
    op.alter_column('notes_internes', 'departement_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Département de rattachement',
               existing_nullable=True)
    op.alter_column('notes_internes', 'domaine_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Domaine de rattachement',
               existing_nullable=True)
    op.alter_column('historique_recherches_police', 'departement_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Département de rattachement',
               existing_nullable=True)
    op.alter_column('historique_recherches_police', 'domaine_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Domaine de rattachement',
               existing_nullable=True)
    op.alter_column('enrolements_police', 'departement_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Département de rattachement',
               existing_nullable=True)
    op.alter_column('enrolements_police', 'domaine_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Domaine de rattachement',
               existing_nullable=True)
    op.alter_column('alertes_police', 'departement_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Département de rattachement',
               existing_nullable=True)
    op.alter_column('alertes_police', 'domaine_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Domaine de rattachement',
               existing_nullable=True)
    op.create_table('ui_module_permissions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('role_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('module_key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('module_label', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('module_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('module_icon', sa.VARCHAR(length=50), server_default=sa.text("'default'::character varying"), autoincrement=False, nullable=True),
    sa.Column('is_enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('is_read_only', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_ui_module_permissions'),
    sa.UniqueConstraint('role_name', 'module_key', name='uq_ui_module_role_module')
    )
    op.create_index('ix_ui_module_role', 'ui_module_permissions', ['role_name'], unique=False)
    op.create_index('ix_ui_module_module', 'ui_module_permissions', ['module_key'], unique=False)
    op.create_index('ix_ui_module_enabled', 'ui_module_permissions', ['is_enabled'], unique=False)
    # ### end Alembic commands ###
