"""phase3_chatbot_documents

ID de révision : f3e49532498b
Révisions précédentes : 8eec7cc31fea
Créée le : 2026-05-31 11:30:59.078392
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Identifiants de révision
revision: str = 'f3e49532498b'
down_revision: Union[str, None] = '8eec7cc31fea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Application de la migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Annulation de la migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
