"""phase3_chatbot_documents

ID de révision : 8eec7cc31fea
Révisions précédentes : 7a1047f579bd
Créée le : 2026-05-31 11:13:26.056924
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Identifiants de révision
revision: str = '8eec7cc31fea'
down_revision: Union[str, None] = '7a1047f579bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Application de la migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('utilisateur_id', sa.UUID(), nullable=False),
    sa.Column('titre', sa.String(length=200), nullable=False),
    sa.Column('date_dernier_message', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modifie_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], name=op.f('fk_conversation_utilisateur_id_utilisateur'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation'))
    )
    op.create_index(op.f('ix_conversation_cree_le'), 'conversation', ['cree_le'], unique=False)
    op.create_index(op.f('ix_conversation_date_dernier_message'), 'conversation', ['date_dernier_message'], unique=False)
    op.create_index(op.f('ix_conversation_utilisateur_id'), 'conversation', ['utilisateur_id'], unique=False)
    op.create_table('document',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('utilisateur_id', sa.UUID(), nullable=False),
    sa.Column('nom_fichier', sa.String(length=255), nullable=False),
    sa.Column('type_mime', sa.String(length=100), nullable=False),
    sa.Column('taille_octets', sa.Integer(), nullable=False),
    sa.Column('contenu_texte', sa.Text(), nullable=False),
    sa.Column('resume', sa.String(length=500), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modifie_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], name=op.f('fk_document_utilisateur_id_utilisateur'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document'))
    )
    op.create_index(op.f('ix_document_cree_le'), 'document', ['cree_le'], unique=False)
    op.create_index(op.f('ix_document_utilisateur_id'), 'document', ['utilisateur_id'], unique=False)
    op.create_table('message',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('auteur', sa.String(length=20), nullable=False),
    sa.Column('contenu', sa.Text(), nullable=False),
    sa.Column('tokens_utilises', sa.Integer(), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modifie_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], name=op.f('fk_message_conversation_id_conversation'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message'))
    )
    op.create_index(op.f('ix_message_conversation_id'), 'message', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_message_cree_le'), 'message', ['cree_le'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Annulation de la migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_cree_le'), table_name='message')
    op.drop_index(op.f('ix_message_conversation_id'), table_name='message')
    op.drop_table('message')
    op.drop_index(op.f('ix_document_utilisateur_id'), table_name='document')
    op.drop_index(op.f('ix_document_cree_le'), table_name='document')
    op.drop_table('document')
    op.drop_index(op.f('ix_conversation_utilisateur_id'), table_name='conversation')
    op.drop_index(op.f('ix_conversation_date_dernier_message'), table_name='conversation')
    op.drop_index(op.f('ix_conversation_cree_le'), table_name='conversation')
    op.drop_table('conversation')
    # ### end Alembic commands ###
