"""Ajout table rapports

ID de révision : d11b8397fdb1
Révisions précédentes : 5f571c30f74b
Créée le : 2026-07-14 22:50:27.952415
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# Identifiants de révision
revision: str = 'd11b8397fdb1'
down_revision: Union[str, None] = '5f571c30f74b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Application de la migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mission_agent',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mission_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('date_limite', sa.Date(), nullable=True),
    sa.Column('statut', sa.String(length=50), nullable=True),
    sa.Column('date_assignation', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_debut', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_completion', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['utilisateur.id'], name=op.f('fk_mission_agent_agent_id_utilisateur'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mission_id'], ['missions_terrain.id'], name=op.f('fk_mission_agent_mission_id_missions_terrain'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mission_agent'))
    )
    op.create_table('rapports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('titre', sa.String(length=255), nullable=False),
    sa.Column('type_rapport', sa.Enum('ACTIVITE', 'MISSION', 'PROGRAMME', 'HEBDOMADAIRE', 'MENSUEL', 'TRIMESTRIEL', name='typerapport'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('statut', sa.Enum('BROUILLON', 'VALIDE', 'ARCHIVE', name='statutrapport'), nullable=False),
    sa.Column('mission_id', sa.UUID(), nullable=True),
    sa.Column('programme_id', sa.UUID(), nullable=True),
    sa.Column('periode_debut', sa.DateTime(timezone=True), nullable=True),
    sa.Column('periode_fin', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cree_par', sa.UUID(), nullable=False),
    sa.Column('date_creation', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_modification', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cree_par'], ['utilisateur.id'], name=op.f('fk_rapports_cree_par_utilisateur'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mission_id'], ['missions_terrain.id'], name=op.f('fk_rapports_mission_id_missions_terrain'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes_ong.id'], name=op.f('fk_rapports_programme_id_programmes_ong'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rapports'))
    )
    op.drop_index('ix_ui_module_enabled', table_name='ui_module_permissions')
    op.drop_index('ix_ui_module_module', table_name='ui_module_permissions')
    op.drop_index('ix_ui_module_role', table_name='ui_module_permissions')
    op.drop_table('ui_module_permissions')
    op.drop_index('ix_demande_changement_role_utilisateur_id', table_name='demande_changement_role')
    op.drop_index('ix_demande_role_utilisateur_statut', table_name='demande_changement_role')
    op.drop_table('demande_changement_role')
    
    # ... (Toutes les autres modifications de colonnes sont conservées, sauf les 3 lignes mrz_ligne supprimées) ...
    
    op.alter_column('verification_cni', 'mrz_ligne_1',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=100), # ✅ CORRIGÉ : On garde 100 pour éviter l'erreur
               existing_nullable=True)
    op.alter_column('verification_cni', 'mrz_ligne_2',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=100), # ✅ CORRIGÉ : On garde 100
               existing_nullable=True)
    op.alter_column('verification_cni', 'mrz_ligne_3',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=100), # ✅ CORRIGÉ : On garde 100
               existing_nullable=True)
               
    op.drop_index('ix_verification_cni_utilisateur_face', table_name='verification_cni')
    op.drop_index('ix_verification_cni_utilisateur_non_supprime', table_name='verification_cni')
    op.alter_column('verification_visuelle', 'score_liveness',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('verification_visuelle', 'est_supprime',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_verification_visuelle_cree_le'), 'verification_visuelle', ['cree_le'], unique=False)
    op.alter_column('verifications_police', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('verifications_police', 'type_verification',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               nullable=True)
    op.alter_column('verifications_police', 'date_verification',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('verifications_police', 'est_signalement_fraude',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    op.drop_index('ix_verifications_police_departement', table_name='verifications_police')
    op.drop_index('ix_verifications_police_domaine', table_name='verifications_police')
    op.create_index(op.f('ix_verifications_police_departement_id'), 'verifications_police', ['departement_id'], unique=False)
    op.create_index(op.f('ix_verifications_police_domaine_id'), 'verifications_police', ['domaine_id'], unique=False)
    op.create_foreign_key(op.f('fk_verifications_police_domaine_id_domaines'), 'verifications_police', 'domaines', ['domaine_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_verifications_police_departement_id_departements'), 'verifications_police', 'departements', ['departement_id'], ['id'], ondelete='SET NULL')
    op.drop_column('verifications_police', 'localisation_lat')
    op.drop_column('verifications_police', 'personne_telephone')
    op.drop_column('verifications_police', 'localisation_adresse')
    op.drop_column('verifications_police', 'motif_verification')
    op.drop_column('verifications_police', 'localisation_lng')
    op.drop_column('verifications_police', 'personne_email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Annulation de la migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verifications_police', sa.Column('personne_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('verifications_police', sa.Column('localisation_lng', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('verifications_police', sa.Column('motif_verification', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('verifications_police', sa.Column('localisation_adresse', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('verifications_police', sa.Column('personne_telephone', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('verifications_police', sa.Column('localisation_lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_verifications_police_departement_id_departements'), 'verifications_police', type_='foreignkey')
    op.drop_constraint(op.f('fk_verifications_police_domaine_id_domaines'), 'verifications_police', type_='foreignkey')
    op.drop_index(op.f('ix_verifications_police_domaine_id'), table_name='verifications_police')
    op.drop_index(op.f('ix_verifications_police_departement_id'), table_name='verifications_police')
    op.create_index('ix_verifications_police_domaine', 'verifications_police', ['domaine_id'], unique=False)
    op.create_index('ix_verifications_police_departement', 'verifications_police', ['departement_id'], unique=False)
    op.alter_column('verifications_police', 'est_signalement_fraude',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=False)
    op.alter_column('verifications_police', 'date_verification',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('verifications_police', 'type_verification',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'identite'::character varying"),
               nullable=False)
    op.alter_column('verifications_police', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_verification_visuelle_cree_le'), table_name='verification_visuelle')
    op.alter_column('verification_visuelle', 'est_supprime',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('verification_visuelle', 'score_liveness',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0.0'),
               existing_nullable=False)
    op.create_index('ix_verification_cni_utilisateur_non_supprime', 'verification_cni', ['utilisateur_id', 'est_supprime'], unique=False)
    op.create_index('ix_verification_cni_utilisateur_face', 'verification_cni', ['utilisateur_id', 'face'], unique=False)
    
    # ✅ CORRIGÉ : On garde le type VARCHAR(100) pour éviter l'erreur de troncature
    op.alter_column('verification_cni', 'mrz_ligne_3',
               existing_type=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('verification_cni', 'mrz_ligne_2',
               existing_type=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('verification_cni', 'mrz_ligne_1',
               existing_type=sa.VARCHAR(length=100),
               existing_nullable=True)
               
    op.add_column('utilisateur', sa.Column('modules_overrides', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True))
    op.add_column('utilisateur', sa.Column('ui_layout', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_utilisateur_superieur_id'), table_name='utilisateur')
    op.drop_index(op.f('ix_utilisateur_domaine_id'), table_name='utilisateur')
    op.drop_index(op.f('ix_utilisateur_departement_id'), table_name='utilisateur')
    op.drop_index('ix_utilisateur_chef', table_name='utilisateur')
    op.alter_column('utilisateur', 'est_supprime',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('utilisateur', 'date_derniere_mise_a_jour_verifications',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment="Date de la dernière mise à jour d'une vérification",
               existing_nullable=True)
    op.alter_column('utilisateur', 'date_verification_cni',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Date de la dernière vérification CNI réussie',
               existing_nullable=True)
    op.alter_column('utilisateur', 'est_cni_verifiee',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               comment="Indique si l'utilisateur a soumis une CNI valide",
               existing_nullable=False)
    op.alter_column('utilisateur', 'date_verification_visage',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Date de la dernière vérification faciale réussie',
               existing_nullable=True)
    op.alter_column('utilisateur', 'est_visage_verifie',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               comment="Indique si l'utilisateur a réussi la vérification faciale",
               existing_nullable=False)
    op.alter_column('utilisateur', 'bonus_score_cumule',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('utilisateur', 'streak_record',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('utilisateur', 'streak_actuel',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('utilisateur', 'score_actuel',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('utilisateur', 'tentatives_connexion_echouees',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('utilisateur', 'est_verrouille',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('utilisateur', 'est_email_verifie',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('utilisateur', 'est_actif',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('utilisateur', 'deux_fa_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_index(op.f('ix_token_reinitialisation_cree_le'), table_name='token_reinitialisation')
    op.alter_column('token_reinitialisation', 'tentative',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('token_reinitialisation', 'est_utilise',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('token_reinitialisation', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.add_column('signalements_fraude', sa.Column('priorite', sa.VARCHAR(length=20), server_default=sa.text("'moyenne'::character varying"), autoincrement=False, nullable=True))
    op.add_column('signalements_fraude', sa.Column('traite_par_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('signalements_fraude', sa.Column('notes_traitement', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_signalements_fraude_departement_id_departements'), 'signalements_fraude', type_='foreignkey')
    op.drop_constraint(op.f('fk_signalements_fraude_domaine_id_domaines'), 'signalements_fraude', type_='foreignkey')
    op.create_foreign_key('signalements_fraude_traite_par_id_fkey', 'signalements_fraude', 'utilisateur', ['traite_par_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_signalements_fraude_domaine_id'), table_name='signalements_fraude')
    op.drop_index(op.f('ix_signalements_fraude_departement_id'), table_name='signalements_fraude')
    op.create_index('ix_signalements_fraude_domaine', 'signalements_fraude', ['domaine_id'], unique=False)
    op.create_index('ix_signalements_fraude_departement', 'signalements_fraude', ['departement_id'], unique=False)
    op.alter_column('signalements_fraude', 'date_signalement',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('signalements_fraude', 'statut',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'en_cours'::character varying"),
               nullable=False)
    op.alter_column('signalements_fraude', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('session_authentification', 'est_revoquee',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('score_historique', 'facteur_attestations',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0.0'),
               comment="Sous-score attestations communautaires (correcteur d'exclusion, max 15)",
               existing_nullable=False)
    op.drop_index(op.f('ix_programmes_ong_domaine_id'), table_name='programmes_ong')
    op.drop_index(op.f('ix_programmes_ong_departement_id'), table_name='programmes_ong')
    op.alter_column('programmes_ong', 'departement_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Département de rattachement',
               existing_nullable=True)
    op.alter_column('programmes_ong', 'domaine_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Domaine de rattachement',
               existing_nullable=True)
    op.alter_column('programmes_ong', 'statut',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'actif'::character varying"),
               nullable=False)
    op.alter_column('programmes_ong', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_constraint(op.f('uq_ordonnances_numero_ordonnance'), 'ordonnances', type_='unique')
    op.drop_index(op.f('ix_ordonnances_domaine_id'), table_name='ordonnances')
    op.drop_index(op.f('ix_ordonnances_departement_id'), table_name='ordonnances')
    op.create_unique_constraint('uq_ordonnances_numero', 'ordonnances', ['numero_ordonnance'])
    op.alter_column('ordonnances', 'departement_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Département de rattachement',
               existing_nullable=True)
    op.alter_column('ordonnances', 'domaine_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Domaine de rattachement',
               existing_nullable=True)
    op.alter_column('ordonnances', 'date_prescription',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('ordonnances', 'statut',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'active'::character varying"),
               nullable=False)
    op.alter_column('ordonnances', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_constraint(op.f('fk_notes_internes_officier_id_utilisateur'), 'notes_internes', type_='foreignkey')
    op.create_foreign_key('notes_internes_officier_id_fkey', 'notes_internes', 'utilisateur', ['officier_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_notes_internes_personne_digiid'), table_name='notes_internes')
    op.drop_index(op.f('ix_notes_internes_officier_id'), table_name='notes_internes')
    op.drop_index(op.f('ix_notes_internes_domaine_id'), table_name='notes_internes')
    op.drop_index(op.f('ix_notes_internes_departement_id'), table_name='notes_internes')
    op.create_index('ix_notes_internes_personne', 'notes_internes', ['personne_digiid'], unique=False)
    op.create_index('ix_notes_internes_officier', 'notes_internes', ['officier_id'], unique=False)
    op.create_index('ix_notes_internes_domaine', 'notes_internes', ['domaine_id'], unique=False)
    op.create_index('ix_notes_internes_departement', 'notes_internes', ['departement_id'], unique=False)
    op.alter_column('notes_internes', 'date_creation',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('notes_internes', 'est_partagee',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('notes_internes', 'est_important',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('notes_internes', 'categorie',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'general'::character varying"),
               existing_nullable=False)
    op.alter_column('notes_internes', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_missions_terrain_domaine_id'), table_name='missions_terrain')
    op.drop_index(op.f('ix_missions_terrain_departement_id'), table_name='missions_terrain')
    op.alter_column('missions_terrain', 'departement_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Département de rattachement',
               existing_nullable=True)
    op.alter_column('missions_terrain', 'domaine_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Domaine de rattachement',
               existing_nullable=True)
    op.alter_column('missions_terrain', 'statut',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'planifiee'::character varying"),
               nullable=False)
    op.alter_column('missions_terrain', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_constraint(op.f('uq_invitations_token'), 'invitations', type_='unique')
    op.drop_index(op.f('ix_invitations_domaine_id'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_departement_id'), table_name='invitations')
    op.alter_column('invitations', 'date_acceptation',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment="Date à laquelle l'invitation a été acceptée",
               existing_nullable=True)
    op.alter_column('invitations', 'date_expiration',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment="Date d'expiration (7 jours par défaut)",
               existing_nullable=False)
    op.alter_column('invitations', 'message',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Message personnalisé optionnel',
               existing_nullable=True)
    op.alter_column('invitations', 'cree_par',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment="Utilisateur qui a créé l'invitation",
               existing_nullable=False)
    op.alter_column('invitations', 'statut',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='en_attente | acceptee | expiree | annulee',
               existing_nullable=False,
               existing_server_default=sa.text("'en_attente'::character varying"))
    op.alter_column('invitations', 'departement_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment="Département d'affectation",
               existing_nullable=True)
    op.alter_column('invitations', 'domaine_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment="Domaine d'affectation",
               existing_nullable=True)
    op.alter_column('invitations', 'role',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Rôle proposé (admin_domaine, chef_police, agent, etc.)',
               existing_nullable=False)
    op.alter_column('invitations', 'token',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='Token sécurisé unique',
               existing_nullable=False)
    op.alter_column('invitations', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Email du destinataire',
               existing_nullable=False)
    op.drop_constraint(op.f('fk_historique_recherches_police_officier_id_utilisateur'), 'historique_recherches_police', type_='foreignkey')
    op.create_foreign_key('historique_recherches_police_officier_id_fkey', 'historique_recherches_police', 'utilisateur', ['officier_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_historique_recherches_police_personne_digiid'), table_name='historique_recherches_police')
    op.drop_index(op.f('ix_historique_recherches_police_officier_id'), table_name='historique_recherches_police')
    op.drop_index(op.f('ix_historique_recherches_police_domaine_id'), table_name='historique_recherches_police')
    op.drop_index(op.f('ix_historique_recherches_police_departement_id'), table_name='historique_recherches_police')
    op.create_index('ix_historique_recherches_police_personne', 'historique_recherches_police', ['personne_digiid'], unique=False)
    op.create_index('ix_historique_recherches_police_officier', 'historique_recherches_police', ['officier_id'], unique=False)
    op.create_index('ix_historique_recherches_police_domaine', 'historique_recherches_police', ['domaine_id'], unique=False)
    op.create_index('ix_historique_recherches_police_departement', 'historique_recherches_police', ['departement_id'], unique=False)
    op.alter_column('historique_recherches_police', 'date_recherche',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('historique_recherches_police', 'criteres_recherche',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('historique_recherches_police', 'type_recherche',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'digiid'::character varying"),
               existing_nullable=False)
    op.alter_column('historique_recherches_police', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_fraude_incident_cree_le'), table_name='fraude_incident')
    op.drop_index(op.f('ix_equipes_departement_id'), table_name='equipes')
    op.drop_index(op.f('ix_equipes_chef_id'), table_name='equipes')
    op.alter_column('equipes', 'chef_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment="Chef de l'équipe",
               existing_nullable=True)
    op.alter_column('equipes', 'departement_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Département parent',
               existing_nullable=False)
    op.alter_column('equipes', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Description optionnelle',
               existing_nullable=True)
    op.alter_column('equipes', 'nom',
               existing_type=sa.VARCHAR(length=150),
               comment=None,
               existing_comment="Nom de l'équipe",
               existing_nullable=False)
    op.drop_constraint(op.f('fk_enrolements_police_officier_id_utilisateur'), 'enrolements_police', type_='foreignkey')
    op.create_foreign_key('enrolements_police_officier_id_fkey', 'enrolements_police', 'utilisateur', ['officier_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_enrolements_police_officier_id'), table_name='enrolements_police')
    op.drop_index(op.f('ix_enrolements_police_domaine_id'), table_name='enrolements_police')
    op.drop_index(op.f('ix_enrolements_police_departement_id'), table_name='enrolements_police')
    op.create_index('ix_enrolements_police_personne', 'enrolements_police', ['personne_digiid'], unique=False)
    op.create_index('ix_enrolements_police_officier', 'enrolements_police', ['officier_id'], unique=False)
    op.create_index('ix_enrolements_police_domaine', 'enrolements_police', ['domaine_id'], unique=False)
    op.create_index('ix_enrolements_police_departement', 'enrolements_police', ['departement_id'], unique=False)
    op.alter_column('enrolements_police', 'date_enrolement',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('enrolements_police', 'documents_uploads',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('enrolements_police', 'donnees_saisies',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('enrolements_police', 'statut',
               existing_type=sa.VARCHAR(length=30),
               server_default=sa.text("'en_attente'::character varying"),
               existing_nullable=False)
    op.alter_column('enrolements_police', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_enrolements_domaine_id'), table_name='enrolements')
    op.drop_index(op.f('ix_enrolements_departement_id'), table_name='enrolements')
    op.alter_column('enrolements', 'departement_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Département de rattachement',
               existing_nullable=True)
    op.alter_column('enrolements', 'domaine_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Domaine de rattachement',
               existing_nullable=True)
    op.alter_column('enrolements', 'date_enrolement',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('enrolements', 'capture_biometrique',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=False)
    op.alter_column('enrolements', 'scan_cni',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=False)
    op.alter_column('enrolements', 'statut',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'en_attente'::character varying"),
               nullable=False)
    op.alter_column('enrolements', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_dossiers_medicaux_domaine_id'), table_name='dossiers_medicaux')
    op.drop_index(op.f('ix_dossiers_medicaux_departement_id'), table_name='dossiers_medicaux')
    op.alter_column('dossiers_medicaux', 'departement_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Département de rattachement',
               existing_nullable=True)
    op.alter_column('dossiers_medicaux', 'domaine_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Domaine de rattachement',
               existing_nullable=True)
    op.alter_column('dossiers_medicaux', 'date_modification',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('dossiers_medicaux', 'date_creation',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('dossiers_medicaux', 'statut',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'ouvert'::character varying"),
               nullable=False)
    op.alter_column('dossiers_medicaux', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_constraint(op.f('uq_domaines_code'), 'domaines', type_='unique')
    op.drop_index('ix_domaines_code_unique', table_name='domaines')
    op.drop_index(op.f('ix_domaines_admin_id'), table_name='domaines')
    op.create_unique_constraint('domaines_code_key', 'domaines', ['code'])
    op.alter_column('domaines', 'motif_suspension',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Raison de la suspension',
               existing_nullable=True)
    op.alter_column('domaines', 'date_suspension',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Date de suspension du domaine',
               existing_nullable=True)
    op.alter_column('domaines', 'est_actif',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Domaine actif ou suspendu',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('domaines', 'admin_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Admin de Domaine responsable',
               existing_nullable=True)
    op.alter_column('domaines', 'region',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Région géographique',
               existing_nullable=True)
    op.alter_column('domaines', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Description optionnelle du domaine',
               existing_nullable=True)
    op.alter_column('domaines', 'code',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Code unique (ex: DOM-NORD)',
               existing_nullable=False)
    op.alter_column('domaines', 'nom',
               existing_type=sa.VARCHAR(length=150),
               comment=None,
               existing_comment='Nom du domaine (ex: Domaine Nord)',
               existing_nullable=False)
    op.alter_column('domaines', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_document_identite_cree_le'), table_name='document_identite')
    op.alter_column('document_identite', 'pays_emetteur',
               existing_type=sa.VARCHAR(length=100),
               server_default=sa.text("'Sénégal'::character varying"),
               existing_nullable=True)
    op.alter_column('document_identite', 'nationalite',
               existing_type=sa.VARCHAR(length=100),
               server_default=sa.text("'Sénégalaise'::character varying"),
               existing_nullable=True)
    op.alter_column('document_identite', 'a_ete_corrige',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('document_identite', 'source',
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("'manuel'::character varying"),
               existing_nullable=True)
    op.alter_column('document_identite', 'est_actif',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('document_identite', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_index('ix_departements_type', table_name='departements')
    op.drop_index(op.f('ix_departements_domaine_id'), table_name='departements')
    op.drop_index(op.f('ix_departements_chef_id'), table_name='departements')
    op.drop_index('ix_departements_actif', table_name='departements')
    op.alter_column('departements', 'capacite_max',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment="Nombre max d'agents (0 = illimité)",
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('departements', 'permissions_personnalisees',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Permissions spécifiques au département',
               existing_nullable=True)
    op.alter_column('departements', 'chef_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Chef de Département responsable',
               existing_nullable=True)
    op.alter_column('departements', 'domaine_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Domaine parent',
               existing_nullable=False)
    op.alter_column('departements', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Description du département',
               existing_nullable=True)
    op.alter_column('departements', 'type_departement',
               existing_type=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='Type: police, medical, ong, agent, admin',
               existing_nullable=False)
    op.alter_column('departements', 'nom',
               existing_type=sa.VARCHAR(length=150),
               comment=None,
               existing_comment='Nom du département',
               existing_nullable=False)
    op.alter_column('departements', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_consultations_domaine_id'), table_name='consultations')
    op.drop_index(op.f('ix_consultations_departement_id'), table_name='consultations')
    op.alter_column('consultations', 'departement_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Département de rattachement',
               existing_nullable=True)
    op.alter_column('consultations', 'domaine_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Domaine de rattachement',
               existing_nullable=True)
    op.alter_column('consultations', 'date_consultation',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('consultations', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_configuration_systeme_cree_le'), table_name='configuration_systeme')
    op.alter_column('configuration_systeme', 'est_actif',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('configuration_systeme', 'niveau_sensibilite',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('configuration_systeme', 'valeur',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=sa.text("'false'::jsonb"),
               existing_nullable=False)
    op.drop_index(op.f('ix_code_verification_cree_le'), table_name='code_verification')
    op.alter_column('code_verification', 'type_verification',
               existing_type=sa.String(length=30),
               server_default=sa.text("'email'::character varying"),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('code_verification', 'est_utilise',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('code_verification', 'tentative',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('code_verification', 'destination',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('code_verification', 'code',
               existing_type=sa.String(length=6),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.alter_column('code_verification', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_beneficiaires_ong_domaine_id'), table_name='beneficiaires_ong')
    op.drop_index(op.f('ix_beneficiaires_ong_departement_id'), table_name='beneficiaires_ong')
    op.alter_column('beneficiaires_ong', 'departement_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Département de rattachement',
               existing_nullable=True)
    op.alter_column('beneficiaires_ong', 'domaine_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Domaine de rattachement',
               existing_nullable=True)
    op.alter_column('beneficiaires_ong', 'statut',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'actif'::character varying"),
               nullable=False)
    op.alter_column('beneficiaires_ong', 'date_inscription',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('beneficiaires_ong', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_attestations_communautaires_id'), table_name='attestations_communautaires')
    op.alter_column('attestations_communautaires', 'est_visible_public',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               comment=None,
               existing_comment='Si True, visible sur le profil public',
               existing_nullable=False)
    op.alter_column('attestations_communautaires', 'est_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               comment=None,
               existing_comment="Si False, l'attestation est désactivée",
               existing_nullable=False)
    op.alter_column('attestations_communautaires', 'signature_numerique',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Signature numérique optionnelle pour non-répudiation',
               existing_nullable=True)
    op.alter_column('attestations_communautaires', 'poids_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('5.0'),
               comment=None,
               existing_comment="Points de score de confiance attribués à l'attesté si approuvée",
               existing_nullable=False)
    op.alter_column('attestations_communautaires', 'date_expiration',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment="Date d'expiration (1 an après approbation si non précisé)",
               existing_nullable=True)
    op.alter_column('attestations_communautaires', 'date_decision',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Date de la décision (approbation/refus)',
               existing_nullable=True)
    op.alter_column('attestations_communautaires', 'date_soumission',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               comment=None,
               existing_comment='Date de création/soumission',
               existing_nullable=False)
    op.alter_column('attestations_communautaires', 'motif_refus',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Motif de refus (si statut = REFUSEE)',
               existing_nullable=True)
    op.alter_column('attestations_communautaires', 'statut',
               existing_type=postgresql.ENUM('EN_ATTENTE', 'APPROUVEE', 'REFUSEE', 'EXPIREE', name='statut_attestation_enum'),
               server_default=sa.text("'EN_ATTENTE'::statut_attestation_enum"),
               comment=None,
               existing_comment="Statut actuel de l'attestation",
               existing_nullable=False)
    op.alter_column('attestations_communautaires', 'lien_nature',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Nature du lien (collègue, voisin, ami, famille, etc.)',
               existing_nullable=True)
    op.alter_column('attestations_communautaires', 'lien_connu_depuis',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment="Depuis quand l'attestant connaît l'attesté",
               existing_nullable=True)
    op.alter_column('attestations_communautaires', 'forces',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Forces/qualités observées chez la personne attestée',
               existing_nullable=True)
    op.alter_column('attestations_communautaires', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment="Description détaillée de l'attestation",
               existing_nullable=True)
    op.alter_column('attestations_communautaires', 'titre',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment="Titre court décrivant l'attestation",
               existing_nullable=False)
    op.alter_column('attestations_communautaires', 'type_attestation',
               existing_type=postgresql.ENUM('identite', 'competence', 'moralite', 'residence', 'activite', 'personnalise', name='type_attestation_enum'),
               server_default=sa.text("'identite'::type_attestation_enum"),
               comment=None,
               existing_comment="Catégorie de l'attestation",
               existing_nullable=False)
    op.alter_column('attestations_communautaires', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_constraint(op.f('fk_alertes_police_officier_id_utilisateur'), 'alertes_police', type_='foreignkey')
    op.create_foreign_key('alertes_police_officier_id_fkey', 'alertes_police', 'utilisateur', ['officier_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_alertes_police_officier_id'), table_name='alertes_police')
    op.drop_index(op.f('ix_alertes_police_domaine_id'), table_name='alertes_police')
    op.drop_index(op.f('ix_alertes_police_departement_id'), table_name='alertes_police')
    op.create_index('ix_alertes_police_officier', 'alertes_police', ['officier_id'], unique=False)
    op.create_index('ix_alertes_police_domaine', 'alertes_police', ['domaine_id'], unique=False)
    op.create_index('ix_alertes_police_departement', 'alertes_police', ['departement_id'], unique=False)
    op.alter_column('alertes_police', 'date_creation',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('alertes_police', 'donnees_liees',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('alertes_police', 'est_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('alertes_police', 'est_lue',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('alertes_police', 'niveau',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'info'::character varying"),
               existing_nullable=False)
    op.alter_column('alertes_police', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_table('demande_changement_role',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('utilisateur_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role_actuel', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('role_demande', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('statut', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('raison_rejet', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('traite_par', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('date_traitement', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('cree_le', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('modifie_le', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['traite_par'], ['utilisateur.id'], name='fk_demande_changement_role_traite_par_utilisateur', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], name='fk_demande_changement_role_utilisateur_id_utilisateur', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_demande_changement_role')
    )
    op.create_index('ix_demande_role_utilisateur_statut', 'demande_changement_role', ['utilisateur_id', 'statut'], unique=False)
    op.create_index('ix_demande_changement_role_utilisateur_id', 'demande_changement_role', ['utilisateur_id'], unique=False)
    op.create_table('ui_module_permissions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('role_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('module_key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('module_label', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('module_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('module_icon', sa.VARCHAR(length=50), server_default=sa.text("'default'::character varying"), autoincrement=False, nullable=True),
    sa.Column('is_enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('is_read_only', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_ui_module_permissions'),
    sa.UniqueConstraint('role_name', 'module_key', name='uq_ui_module_role_module')
    )
    op.create_index('ix_ui_module_role', 'ui_module_permissions', ['role_name'], unique=False)
    op.create_index('ix_ui_module_module', 'ui_module_permissions', ['module_key'], unique=False)
    op.create_index('ix_ui_module_enabled', 'ui_module_permissions', ['is_enabled'], unique=False)
    op.drop_table('rapports')
    op.drop_table('mission_agent')
    # ### end Alembic commands ###
