"""ajout tables permis_conduire et assurances_auto

ID de révision : ced3f38acfce
Révisions précédentes : c7a8b9d0e1f2
Créée le : 2026-08-01 16:08:18.565682
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# Identifiants de révision
revision: str = 'ced3f38acfce'
down_revision: Union[str, None] = 'c7a8b9d0e1f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Application de la migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assurances_auto',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('utilisateur_id', sa.UUID(), nullable=False),
    sa.Column('compagnie_assurance', sa.String(), nullable=False),
    sa.Column('numero_contrat', sa.String(), nullable=False),
    sa.Column('immatriculation', sa.String(), nullable=False),
    sa.Column('marque_vehicule', sa.String(), nullable=True),
    sa.Column('modele_vehicule', sa.String(), nullable=True),
    sa.Column('date_effet', sa.Date(), nullable=False),
    sa.Column('date_expiration', sa.Date(), nullable=False),
    sa.Column('est_active', sa.Boolean(), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mis_a_jour_le', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], name=op.f('fk_assurances_auto_utilisateur_id_utilisateur'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assurances_auto'))
    )
    op.create_index(op.f('ix_assurances_auto_id'), 'assurances_auto', ['id'], unique=False)
    op.create_index(op.f('ix_assurances_auto_immatriculation'), 'assurances_auto', ['immatriculation'], unique=False)
    op.create_index(op.f('ix_assurances_auto_numero_contrat'), 'assurances_auto', ['numero_contrat'], unique=False)
    op.create_index(op.f('ix_assurances_auto_utilisateur_id'), 'assurances_auto', ['utilisateur_id'], unique=False)
    op.create_table('permis_conduire',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('utilisateur_id', sa.UUID(), nullable=False),
    sa.Column('numero_permis', sa.String(), nullable=False),
    sa.Column('categories', sa.JSON(), nullable=True),
    sa.Column('date_premiere_delivrance', sa.Date(), nullable=True),
    sa.Column('date_delivrance', sa.Date(), nullable=False),
    sa.Column('date_expiration', sa.Date(), nullable=False),
    sa.Column('lieu_delivrance', sa.String(), nullable=True),
    sa.Column('autorite_delivrance', sa.String(), nullable=True),
    sa.Column('est_valide', sa.Boolean(), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mis_a_jour_le', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], name=op.f('fk_permis_conduire_utilisateur_id_utilisateur'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permis_conduire'))
    )
    op.create_index(op.f('ix_permis_conduire_id'), 'permis_conduire', ['id'], unique=False)
    op.create_index(op.f('ix_permis_conduire_numero_permis'), 'permis_conduire', ['numero_permis'], unique=True)
    op.create_index(op.f('ix_permis_conduire_utilisateur_id'), 'permis_conduire', ['utilisateur_id'], unique=False)
    op.drop_index('ix_ui_module_enabled', table_name='ui_module_permissions')
    op.drop_index('ix_ui_module_module', table_name='ui_module_permissions')
    op.drop_index('ix_ui_module_role', table_name='ui_module_permissions')
    op.drop_table('ui_module_permissions')
    op.drop_constraint('uq_ordonnances_numero', 'ordonnances', type_='unique')
    op.drop_constraint('signalements_fraude_traite_par_id_fkey', 'signalements_fraude', type_='foreignkey')
    op.drop_column('signalements_fraude', 'priorite')
    op.drop_column('signalements_fraude', 'notes_traitement')
    op.drop_column('signalements_fraude', 'traite_par_id')
    op.drop_column('verifications_police', 'localisation_adresse')
    op.drop_column('verifications_police', 'motif_verification')
    op.drop_column('verifications_police', 'localisation_lng')
    op.drop_column('verifications_police', 'personne_telephone')
    op.drop_column('verifications_police', 'personne_email')
    op.drop_column('verifications_police', 'localisation_lat')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Annulation de la migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verifications_police', sa.Column('localisation_lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('verifications_police', sa.Column('personne_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('verifications_police', sa.Column('personne_telephone', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('verifications_police', sa.Column('localisation_lng', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('verifications_police', sa.Column('motif_verification', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('verifications_police', sa.Column('localisation_adresse', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('signalements_fraude', sa.Column('traite_par_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('signalements_fraude', sa.Column('notes_traitement', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('signalements_fraude', sa.Column('priorite', sa.VARCHAR(length=20), server_default=sa.text("'moyenne'::character varying"), autoincrement=False, nullable=True))
    op.create_foreign_key('signalements_fraude_traite_par_id_fkey', 'signalements_fraude', 'utilisateur', ['traite_par_id'], ['id'], ondelete='SET NULL')
    op.create_unique_constraint('uq_ordonnances_numero', 'ordonnances', ['numero_ordonnance'])
    op.create_table('ui_module_permissions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('role_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('module_key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('module_label', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('module_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('module_icon', sa.VARCHAR(length=50), server_default=sa.text("'default'::character varying"), autoincrement=False, nullable=True),
    sa.Column('is_enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('is_read_only', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_ui_module_permissions'),
    sa.UniqueConstraint('role_name', 'module_key', name='uq_ui_module_role_module')
    )
    op.create_index('ix_ui_module_role', 'ui_module_permissions', ['role_name'], unique=False)
    op.create_index('ix_ui_module_module', 'ui_module_permissions', ['module_key'], unique=False)
    op.create_index('ix_ui_module_enabled', 'ui_module_permissions', ['is_enabled'], unique=False)
    op.drop_index(op.f('ix_permis_conduire_utilisateur_id'), table_name='permis_conduire')
    op.drop_index(op.f('ix_permis_conduire_numero_permis'), table_name='permis_conduire')
    op.drop_index(op.f('ix_permis_conduire_id'), table_name='permis_conduire')
    op.drop_table('permis_conduire')
    op.drop_index(op.f('ix_assurances_auto_utilisateur_id'), table_name='assurances_auto')
    op.drop_index(op.f('ix_assurances_auto_numero_contrat'), table_name='assurances_auto')
    op.drop_index(op.f('ix_assurances_auto_immatriculation'), table_name='assurances_auto')
    op.drop_index(op.f('ix_assurances_auto_id'), table_name='assurances_auto')
    op.drop_table('assurances_auto')
    # ### end Alembic commands ###
