"""ajout colonne officier_nom verifications_police

ID de révision : 9de5396d8ac6
Révisions précédentes : 8a282900abf1
Créée le : 2026-08-06 17:08:29.108997
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# Identifiants de révision
revision: str = '9de5396d8ac6'
down_revision: Union[str, None] = '8a282900abf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Application de la migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ui_module_enabled', table_name='ui_module_permissions')
    op.drop_index('ix_ui_module_module', table_name='ui_module_permissions')
    op.drop_index('ix_ui_module_role', table_name='ui_module_permissions')
    op.drop_table('ui_module_permissions')
    op.drop_constraint('uq_ordonnances_numero', 'ordonnances', type_='unique')
    op.alter_column('signalements_fraude', 'priorite',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=True)
    op.create_index(op.f('ix_signalements_fraude_traite_par_id'), 'signalements_fraude', ['traite_par_id'], unique=False)
    op.alter_column('verifications_police', 'motif_verification',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('verifications_police', 'localisation_adresse',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.add_column('verifications_police', sa.Column('officier_nom', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Annulation de la migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('verifications_police', 'localisation_adresse',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('verifications_police', 'motif_verification',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_signalements_fraude_traite_par_id'), table_name='signalements_fraude')
    op.alter_column('signalements_fraude', 'priorite',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'moyenne'::character varying"),
               existing_nullable=True)
    op.create_unique_constraint('uq_ordonnances_numero', 'ordonnances', ['numero_ordonnance'])
    op.create_table('ui_module_permissions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('role_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('module_key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('module_label', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('module_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('module_icon', sa.VARCHAR(length=50), server_default=sa.text("'default'::character varying"), autoincrement=False, nullable=True),
    sa.Column('is_enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('is_read_only', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_ui_module_permissions'),
    sa.UniqueConstraint('role_name', 'module_key', name='uq_ui_module_role_module')
    )
    op.create_index('ix_ui_module_role', 'ui_module_permissions', ['role_name'], unique=False)
    op.create_index('ix_ui_module_module', 'ui_module_permissions', ['module_key'], unique=False)
    op.create_index('ix_ui_module_enabled', 'ui_module_permissions', ['is_enabled'], unique=False)
    # ### end Alembic commands ###
