"""initial

ID de révision : 13089436590d
Révisions précédentes : 
Créée le : 2026-05-28 11:30:15.468257
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Identifiants de révision
revision: str = '13089436590d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Application de la migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom_technique', sa.String(length=50), nullable=False),
    sa.Column('nom_affichage', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('niveau_hierarchie', sa.Integer(), nullable=False),
    sa.Column('cree_le', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modifie_le', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role'))
    )
    op.create_index(op.f('ix_role_cree_le'), 'role', ['cree_le'], unique=False)
    op.create_index(op.f('ix_role_nom_technique'), 'role', ['nom_technique'], unique=True)
    op.create_table('utilisateur',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('digiid_public', sa.String(length=16), nullable=True),
    sa.Column('email_chiffre', sa.String(length=512), nullable=False),
    sa.Column('email_hash', sa.String(length=64), nullable=False),
    sa.Column('mot_de_passe_hash', sa.String(length=255), nullable=False),
    sa.Column('prenom_chiffre', sa.String(length=512), nullable=True),
    sa.Column('nom_chiffre', sa.String(length=512), nullable=True),
    sa.Column('telephone_chiffre', sa.String(length=512), nullable=True),
    sa.Column('ville', sa.String(length=100), nullable=True),
    sa.Column('pays', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('secret_2fa_chiffre', sa.String(length=512), nullable=True),
    sa.Column('deux_fa_active', sa.Boolean(), nullable=False),
    sa.Column('est_actif', sa.Boolean(), nullable=False),
    sa.Column('est_email_verifie', sa.Boolean(), nullable=False),
    sa.Column('est_verrouille', sa.Boolean(), nullable=False),
    sa.Column('date_verrouillage', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tentatives_connexion_echouees', sa.Integer(), nullable=False),
    sa.Column('score_actuel', sa.Integer(), nullable=True),
    sa.Column('date_dernier_calcul_score', sa.DateTime(timezone=True), nullable=True),
    sa.Column('empreinte_faciale', sa.LargeBinary(), nullable=True),
    sa.Column('est_supprime', sa.Boolean(), nullable=False),
    sa.Column('date_suppression', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_derniere_connexion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_derniere_connexion', sa.String(length=45), nullable=True),
    sa.Column('cree_le', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modifie_le', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_utilisateur'))
    )
    op.create_index(op.f('ix_utilisateur_cree_le'), 'utilisateur', ['cree_le'], unique=False)
    op.create_index(op.f('ix_utilisateur_digiid_public'), 'utilisateur', ['digiid_public'], unique=True)
    op.create_index(op.f('ix_utilisateur_email_hash'), 'utilisateur', ['email_hash'], unique=True)
    op.create_index(op.f('ix_utilisateur_est_actif'), 'utilisateur', ['est_actif'], unique=False)
    op.create_index(op.f('ix_utilisateur_est_supprime'), 'utilisateur', ['est_supprime'], unique=False)
    op.create_index(op.f('ix_utilisateur_role'), 'utilisateur', ['role'], unique=False)
    op.create_index('ix_utilisateur_role_actif', 'utilisateur', ['role', 'est_actif'], unique=False)
    op.create_index('ix_utilisateur_role_supprime', 'utilisateur', ['role', 'est_supprime'], unique=False)
    op.create_table('consentement',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('utilisateur_id', sa.UUID(), nullable=False),
    sa.Column('categorie', sa.String(length=100), nullable=False),
    sa.Column('version_texte', sa.String(length=20), nullable=False),
    sa.Column('texte_accepte', sa.Text(), nullable=False),
    sa.Column('est_accorde', sa.Boolean(), nullable=False),
    sa.Column('date_accord', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_retrait', sa.DateTime(timezone=True), nullable=True),
    sa.Column('adresse_ip_accord', sa.String(length=45), nullable=True),
    sa.Column('cree_le', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modifie_le', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], name=op.f('fk_consentement_utilisateur_id_utilisateur'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consentement'))
    )
    op.create_index(op.f('ix_consentement_categorie'), 'consentement', ['categorie'], unique=False)
    op.create_index(op.f('ix_consentement_cree_le'), 'consentement', ['cree_le'], unique=False)
    op.create_index(op.f('ix_consentement_utilisateur_id'), 'consentement', ['utilisateur_id'], unique=False)
    op.create_table('journal_audit',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date_evenement', sa.DateTime(timezone=True), nullable=False),
    sa.Column('utilisateur_id', sa.UUID(), nullable=True),
    sa.Column('role_acteur', sa.String(length=50), nullable=True),
    sa.Column('type_evenement', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('adresse_ip', sa.String(length=45), nullable=True),
    sa.Column('agent_utilisateur', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.Column('donnees_supplementaires', sa.JSON(), nullable=True),
    sa.Column('score_risque', sa.Integer(), nullable=True),
    sa.Column('signature_cryptographique', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], name=op.f('fk_journal_audit_utilisateur_id_utilisateur'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_journal_audit'))
    )
    op.create_index('ix_audit_type_date', 'journal_audit', ['type_evenement', 'date_evenement'], unique=False)
    op.create_index('ix_audit_utilisateur_date', 'journal_audit', ['utilisateur_id', 'date_evenement'], unique=False)
    op.create_index(op.f('ix_journal_audit_adresse_ip'), 'journal_audit', ['adresse_ip'], unique=False)
    op.create_index(op.f('ix_journal_audit_date_evenement'), 'journal_audit', ['date_evenement'], unique=False)
    op.create_index(op.f('ix_journal_audit_request_id'), 'journal_audit', ['request_id'], unique=False)
    op.create_index(op.f('ix_journal_audit_type_evenement'), 'journal_audit', ['type_evenement'], unique=False)
    op.create_index(op.f('ix_journal_audit_utilisateur_id'), 'journal_audit', ['utilisateur_id'], unique=False)
    op.create_table('session_authentification',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('utilisateur_id', sa.UUID(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=64), nullable=False),
    sa.Column('adresse_ip', sa.String(length=45), nullable=False),
    sa.Column('agent_utilisateur', sa.Text(), nullable=True),
    sa.Column('ville_estimee', sa.String(length=100), nullable=True),
    sa.Column('pays_estime', sa.String(length=50), nullable=True),
    sa.Column('date_expiration', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_derniere_utilisation', sa.DateTime(timezone=True), nullable=False),
    sa.Column('est_revoquee', sa.Boolean(), nullable=False),
    sa.Column('raison_revocation', sa.String(length=100), nullable=True),
    sa.Column('cree_le', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modifie_le', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], name=op.f('fk_session_authentification_utilisateur_id_utilisateur'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_authentification'))
    )
    op.create_index(op.f('ix_session_authentification_cree_le'), 'session_authentification', ['cree_le'], unique=False)
    op.create_index(op.f('ix_session_authentification_refresh_token_hash'), 'session_authentification', ['refresh_token_hash'], unique=True)
    op.create_index(op.f('ix_session_authentification_utilisateur_id'), 'session_authentification', ['utilisateur_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Annulation de la migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_authentification_utilisateur_id'), table_name='session_authentification')
    op.drop_index(op.f('ix_session_authentification_refresh_token_hash'), table_name='session_authentification')
    op.drop_index(op.f('ix_session_authentification_cree_le'), table_name='session_authentification')
    op.drop_table('session_authentification')
    op.drop_index(op.f('ix_journal_audit_utilisateur_id'), table_name='journal_audit')
    op.drop_index(op.f('ix_journal_audit_type_evenement'), table_name='journal_audit')
    op.drop_index(op.f('ix_journal_audit_request_id'), table_name='journal_audit')
    op.drop_index(op.f('ix_journal_audit_date_evenement'), table_name='journal_audit')
    op.drop_index(op.f('ix_journal_audit_adresse_ip'), table_name='journal_audit')
    op.drop_index('ix_audit_utilisateur_date', table_name='journal_audit')
    op.drop_index('ix_audit_type_date', table_name='journal_audit')
    op.drop_table('journal_audit')
    op.drop_index(op.f('ix_consentement_utilisateur_id'), table_name='consentement')
    op.drop_index(op.f('ix_consentement_cree_le'), table_name='consentement')
    op.drop_index(op.f('ix_consentement_categorie'), table_name='consentement')
    op.drop_table('consentement')
    op.drop_index('ix_utilisateur_role_supprime', table_name='utilisateur')
    op.drop_index('ix_utilisateur_role_actif', table_name='utilisateur')
    op.drop_index(op.f('ix_utilisateur_role'), table_name='utilisateur')
    op.drop_index(op.f('ix_utilisateur_est_supprime'), table_name='utilisateur')
    op.drop_index(op.f('ix_utilisateur_est_actif'), table_name='utilisateur')
    op.drop_index(op.f('ix_utilisateur_email_hash'), table_name='utilisateur')
    op.drop_index(op.f('ix_utilisateur_digiid_public'), table_name='utilisateur')
    op.drop_index(op.f('ix_utilisateur_cree_le'), table_name='utilisateur')
    op.drop_table('utilisateur')
    op.drop_index(op.f('ix_role_nom_technique'), table_name='role')
    op.drop_index(op.f('ix_role_cree_le'), table_name='role')
    op.drop_table('role')
    # ### end Alembic commands ###
