"""ajout colonne officier_nom verifications_police

ID de révision : 8c2972f8b688
Révisions précédentes : 9de5396d8ac6
Créée le : 2026-08-06 17:09:00.884532
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Identifiants de révision
revision: str = '8c2972f8b688'
down_revision: Union[str, None] = '9de5396d8ac6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Application de la migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_ordonnances_numero', 'ordonnances', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Annulation de la migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_ordonnances_numero', 'ordonnances', ['numero_ordonnance'])
    # ### end Alembic commands ###
