"""ajout date_naissance et lieu_naissance a permis_conduire

ID de révision : 8a282900abf1
Révisions précédentes : 20260804_0900_ajout_date_naissance_permis_assurance
Créée le : 2026-08-04 00:27:11.698409
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Identifiants de révision
revision: str = '8a282900abf1'
down_revision: Union[str, None] = '20260804_0900_ajout_date_naissance_permis_assurance'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Application de la migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assurances_auto', sa.Column('date_naissance', sa.Date(), nullable=True))
    op.add_column('assurances_auto', sa.Column('lieu_naissance', sa.String(length=255), nullable=True))
    op.drop_constraint('uq_ordonnances_numero', 'ordonnances', type_='unique')
    op.add_column('permis_conduire', sa.Column('date_naissance', sa.Date(), nullable=True))
    op.add_column('permis_conduire', sa.Column('lieu_naissance', sa.String(length=255), nullable=True))
    op.drop_constraint('signalements_fraude_traite_par_id_fkey', 'signalements_fraude', type_='foreignkey')
    op.drop_column('signalements_fraude', 'traite_par_id')
    op.drop_column('signalements_fraude', 'priorite')
    op.drop_column('signalements_fraude', 'notes_traitement')
    op.drop_column('verifications_police', 'personne_telephone')
    op.drop_column('verifications_police', 'personne_email')
    op.drop_column('verifications_police', 'motif_verification')
    op.drop_column('verifications_police', 'localisation_lat')
    op.drop_column('verifications_police', 'localisation_lng')
    op.drop_column('verifications_police', 'localisation_adresse')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Annulation de la migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verifications_police', sa.Column('localisation_adresse', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('verifications_police', sa.Column('localisation_lng', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('verifications_police', sa.Column('localisation_lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('verifications_police', sa.Column('motif_verification', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('verifications_police', sa.Column('personne_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('verifications_police', sa.Column('personne_telephone', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('signalements_fraude', sa.Column('notes_traitement', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('signalements_fraude', sa.Column('priorite', sa.VARCHAR(length=20), server_default=sa.text("'moyenne'::character varying"), autoincrement=False, nullable=True))
    op.add_column('signalements_fraude', sa.Column('traite_par_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('signalements_fraude_traite_par_id_fkey', 'signalements_fraude', 'utilisateur', ['traite_par_id'], ['id'], ondelete='SET NULL')
    op.drop_column('permis_conduire', 'lieu_naissance')
    op.drop_column('permis_conduire', 'date_naissance')
    op.create_unique_constraint('uq_ordonnances_numero', 'ordonnances', ['numero_ordonnance'])
    op.drop_column('assurances_auto', 'lieu_naissance')
    op.drop_column('assurances_auto', 'date_naissance')
    # ### end Alembic commands ###
