"""ajout_colonnes_bagages_et_passagers

ID de révision : 22500ece2f6e
Révisions précédentes : 15f0e9cc68d4
Créée le : 2026-10-05 21:28:48.729679
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Identifiants de révision
revision: str = '22500ece2f6e'
down_revision: Union[str, None] = '15f0e9cc68d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Application de la migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('colis', sa.Column('nombre_bagages', sa.Integer(), server_default='1', nullable=False))
    op.drop_constraint('uq_ordonnances_numero', 'ordonnances', type_='unique')
    op.add_column('suivi_familial', sa.Column('type_passager', sa.String(length=10), server_default='enfant', nullable=False))
    op.add_column('suivi_familial', sa.Column('telephone_passager', sa.String(length=30), nullable=True))
    op.add_column('suivi_familial', sa.Column('acheteur_nom', sa.String(length=150), nullable=True))
    op.add_column('suivi_familial', sa.Column('acheteur_tel', sa.String(length=30), nullable=True))
    op.add_column('suivi_familial', sa.Column('proche_nom', sa.String(length=150), nullable=True))
    op.add_column('suivi_familial', sa.Column('proche_telephone', sa.String(length=30), nullable=True))
    op.add_column('suivi_familial', sa.Column('nombre_bagages', sa.Integer(), server_default='1', nullable=False))
    op.add_column('suivi_familial', sa.Column('chauffeur_id', sa.UUID(), nullable=True))
    op.add_column('suivi_familial', sa.Column('pre_alerte_envoyee', sa.Boolean(), server_default='false', nullable=False))
    op.create_index('ix_suivi_familial_chauffeur', 'suivi_familial', ['chauffeur_id'], unique=False)
    op.create_foreign_key(op.f('fk_suivi_familial_chauffeur_id_utilisateur'), 'suivi_familial', 'utilisateur', ['chauffeur_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Annulation de la migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_suivi_familial_chauffeur_id_utilisateur'), 'suivi_familial', type_='foreignkey')
    op.drop_index('ix_suivi_familial_chauffeur', table_name='suivi_familial')
    op.drop_column('suivi_familial', 'pre_alerte_envoyee')
    op.drop_column('suivi_familial', 'chauffeur_id')
    op.drop_column('suivi_familial', 'nombre_bagages')
    op.drop_column('suivi_familial', 'proche_telephone')
    op.drop_column('suivi_familial', 'proche_nom')
    op.drop_column('suivi_familial', 'acheteur_tel')
    op.drop_column('suivi_familial', 'acheteur_nom')
    op.drop_column('suivi_familial', 'telephone_passager')
    op.drop_column('suivi_familial', 'type_passager')
    op.create_unique_constraint('uq_ordonnances_numero', 'ordonnances', ['numero_ordonnance'])
    op.drop_column('colis', 'nombre_bagages')
    # ### end Alembic commands ###
