"""phase2_score_historique

ID de révision : ff00209b6463
Révisions précédentes : f3e49532498b
Créée le : 2026-06-03 14:42:11.402527
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Identifiants de révision
revision: str = 'ff00209b6463'
down_revision: Union[str, None] = 'f3e49532498b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Application de la migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activite_quotidienne',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('utilisateur_id', sa.UUID(), nullable=False),
    sa.Column('jour', sa.Date(), nullable=False),
    sa.Column('nombre_actions', sa.Integer(), nullable=False),
    sa.Column('derniere_action', sa.String(length=50), nullable=True),
    sa.Column('date_premiere_action', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_derniere_action', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], name=op.f('fk_activite_quotidienne_utilisateur_id_utilisateur'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activite_quotidienne')),
    sa.UniqueConstraint('utilisateur_id', 'jour', name='uq_activite_utilisateur_jour')
    )
    op.create_index(op.f('ix_activite_quotidienne_jour'), 'activite_quotidienne', ['jour'], unique=False)
    op.create_index(op.f('ix_activite_quotidienne_utilisateur_id'), 'activite_quotidienne', ['utilisateur_id'], unique=False)
    op.create_table('badge',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('utilisateur_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('date_obtention', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bonus_score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], name=op.f('fk_badge_utilisateur_id_utilisateur'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_badge')),
    sa.UniqueConstraint('utilisateur_id', 'code', name='uq_badge_utilisateur_code')
    )
    op.create_index(op.f('ix_badge_code'), 'badge', ['code'], unique=False)
    op.create_index(op.f('ix_badge_utilisateur_id'), 'badge', ['utilisateur_id'], unique=False)
    op.create_table('notification',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('utilisateur_id', sa.UUID(), nullable=False),
    sa.Column('type_notification', sa.String(length=20), nullable=False),
    sa.Column('categorie', sa.String(length=30), nullable=False),
    sa.Column('titre', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('lien_action', sa.String(length=200), nullable=True),
    sa.Column('est_lue', sa.Boolean(), nullable=False),
    sa.Column('date_lecture', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modifie_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], name=op.f('fk_notification_utilisateur_id_utilisateur'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification'))
    )
    op.create_index(op.f('ix_notification_categorie'), 'notification', ['categorie'], unique=False)
    op.create_index(op.f('ix_notification_cree_le'), 'notification', ['cree_le'], unique=False)
    op.create_index(op.f('ix_notification_est_lue'), 'notification', ['est_lue'], unique=False)
    op.create_index(op.f('ix_notification_utilisateur_id'), 'notification', ['utilisateur_id'], unique=False)
    op.create_table('parrainage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parrain_id', sa.UUID(), nullable=False),
    sa.Column('filleul_id', sa.UUID(), nullable=False),
    sa.Column('code_utilise', sa.String(length=8), nullable=False),
    sa.Column('date_parrainage', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['filleul_id'], ['utilisateur.id'], name=op.f('fk_parrainage_filleul_id_utilisateur'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parrain_id'], ['utilisateur.id'], name=op.f('fk_parrainage_parrain_id_utilisateur'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parrainage'))
    )
    op.create_index(op.f('ix_parrainage_filleul_id'), 'parrainage', ['filleul_id'], unique=True)
    op.create_index(op.f('ix_parrainage_parrain_id'), 'parrainage', ['parrain_id'], unique=False)
    op.alter_column('document', 'resume',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=2000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Annulation de la migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document', 'resume',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.drop_index(op.f('ix_parrainage_parrain_id'), table_name='parrainage')
    op.drop_index(op.f('ix_parrainage_filleul_id'), table_name='parrainage')
    op.drop_table('parrainage')
    op.drop_index(op.f('ix_notification_utilisateur_id'), table_name='notification')
    op.drop_index(op.f('ix_notification_est_lue'), table_name='notification')
    op.drop_index(op.f('ix_notification_cree_le'), table_name='notification')
    op.drop_index(op.f('ix_notification_categorie'), table_name='notification')
    op.drop_table('notification')
    op.drop_index(op.f('ix_badge_utilisateur_id'), table_name='badge')
    op.drop_index(op.f('ix_badge_code'), table_name='badge')
    op.drop_table('badge')
    op.drop_index(op.f('ix_activite_quotidienne_utilisateur_id'), table_name='activite_quotidienne')
    op.drop_index(op.f('ix_activite_quotidienne_jour'), table_name='activite_quotidienne')
    op.drop_table('activite_quotidienne')
    # ### end Alembic commands ###
